[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
required-root-patterns = ["biome.json"]

[language-server.lsp-ai]
command = "lsp-ai"
[language-server.lsp-ai.config.memory]
file_store = { }
[language-server.lsp-ai.config.models.deepseek-coder]
type = "ollama"
model = "deepseek-coder:1.3b-base"
[language-server.lsp-ai.config.completion]
model = "deepseek-coder"
[language-server.lsp-ai.config.completion.parameters]
max_context = 2000
[language-server.lsp-ai.config.completion.options]
num_predict = 32
[language-server.lsp-ai.config.completion.parameters.fim]
start = "<｜fim▁begin｜>"
middle = "<｜fim▁hole｜>"
end = "<｜fim▁end｜>"

[language-server.golangci-lint.config]
command = "golangci-lint-langserver" 
args = ["run", "--out-format", "json", "--issues-exit-code=1"]

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "lsp-ai" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "lsp-ai" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "lsp-ai" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "lsp-ai" ]

[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer", "lsp-ai" ]

[[language]]
name = "go"
language-servers = [ "gopls", "golangci-lint", "lsp-ai" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "python"
language-servers = [ "pyright" ]

[[language]]
name = "dockerfile"
scope = "source.dockerfile"
file-types = ["Dockerfile", { glob = "*Dockerfile*" }]

[[grammar]]
name = "dockerfile"
source = { git = "https://github.com/camdencheek/tree-sitter-dockerfile", rev = "main" }
