[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
required-root-patterns = ["biome.json"]

[language-server.kotlin-ls]
command = "kotlin-ls"
args = ["--stdio"]
timeout = 60
required-root-patterns = ["build.gradle", "build.gradle.kts", "pom.xml"]


[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer" ]

# [[language]]
# name = "go"
# language-servers = [ "gopls", "golangci-lint" ]
# auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "python"
language-servers = [ "pyright" ]

[[language]]
name = "dockerfile"
scope = "source.dockerfile"
file-types = ["Dockerfile", { glob = "*Dockerfile*" }]

[[grammar]]
name = "dockerfile"
source = { git = "https://github.com/camdencheek/tree-sitter-dockerfile", rev = "main" }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "kotlin"
scope = "source.kotlin"
injection-regex = "kotlin"
file-types = ["kt", "kts"]
roots = ["build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts", "pom.xml"]
auto-format = true
language-servers = ["kotlin-ls"]
