[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
required-root-patterns = ["biome.json"]

[language-server.golangci-lint]
command = "golangci-lint-langserver" 
args = ["run", "--out-format", "json", "--issues-exit-code=1"]

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer" ]

[[language]]
name = "go"
language-servers = [ "gopls", "golangci-lint" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "python"
language-servers = [ "pyright" ]

[[language]]
name = "dockerfile"
scope = "source.dockerfile"
file-types = ["Dockerfile", { glob = "*Dockerfile*" }]

[[grammar]]
name = "dockerfile"
source = { git = "https://github.com/camdencheek/tree-sitter-dockerfile", rev = "main" }
